server:
  port: 40200
spring:
  profiles:
    active: local
  application:
    name: pbear-app-subway-business
  data:
    mongodb:
      database: subway
seoul-open-data:
  subway:
    schema: http
    host: openapi.seoul.go.kr
    port: 8088
    station:
      path: /{apiKey}/json/subwayStationMaster/{startIndex}/{endIndex}
    cardSubwayStatesNew:
      path: /{apiKey}/json/CardSubwayStatsNew/{startIndex}/{endIndex}/{yyyyMMdd}