server:
  port: 40400
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/xml, text/plain, application/json, application/javascript
spring:
  profiles:
    active: local
  application:
    name: pbear-app-wow
  data:
    mongodb:
      database: wow
blizzard:
  oauth-url: https://oauth.battle.net
  api-url: https://kr.api.blizzard.com