management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
    enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metric, loggers